services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    command: >
      sh -c "bundle exec bin/rails db:migrate db:seed && bundle exec rails s -b 0.0.0.0"
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - ./backend/config/master.key:/app/config/master.key:ro
      - ~/.aws:/root/.aws
    environment:
      - PORT=3001
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:my_secure_password@db:5432/membership_portal_dev
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}        
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: membership_portal_dev
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5