services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
      - ./backend/config/master.key:/app/config/master.key:ro
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/membership_portal_dev
      # - RAILS_MASTER_KEY=f8b5a95cb36ef0877f0cf121f8d6a4b3
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # Specify the password here
      POSTGRES_DB: membership_portal_dev
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data