services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
    env_files:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # Specify the password here
      POSTGRES_DB: membership_portal_dev
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data